# Temporarily disabled due to lag caused by mechanisms that frequently place other blocks. Enable it only if you're sure such mechanisms aren't present in your modpack or won't appear in your field of view too often.
enabledOreScanner: false
