name = "Craftoria"
author = "TeamAOE"
version = "1.36.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e6ab59a7a889dab78a0be4ed88b0df9b4776208b8761bb2c2cad97181e9b731"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
