name = "Craftoria"
author = "TeamAOE"
version = "1.33.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dde7f7c5c7bbf8c2cc8e836f4a7c53bd20627123a9a8286c874c986d4e119af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
