name = "Craftoria"
author = "TeamAOE"
version = "1.33.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "860fc7e4a7701a2f0756774645bd9b62b953046236e0bd1ba015e01c959b93ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
