name = "Craftoria"
author = "TeamAOE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef7b0951a88b13a3afdf01ec7a66e5b107f2fed06916ef78ce5977e1313379fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
