name = "Craftoria"
author = "TeamAOE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ffaf24aa85155a780666b8620c82386beba7a72b3a18ada2406ce4aebecd04b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
