name = "Craftoria"
author = "TeamAOE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03dd5952ae29aaa08a78361049b2ed1efd60da89fbb1b1de7ccfa5527878afc7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
