#Settings for configuring Electric Pumps and Fluidic Plenishers
[pump]
	#Amount of Heavy Water in mB that is extracted per block of Water by the Advanced Electric Pump with a Filter Upgrade.
	# Default: 100
	# Range: 1 ~ 1000
	heavyWaterAmount = 100
