StartupEvents.registry('block', event => {

	event.create('craftoria:completionist_cup').displayName('Completionist Cup').defaultCutout()

	event.create('craftoria:blaze_block')
		.displayName('Blaze Block')
		.material('minecraft:deepslate_bricks')
		.hardness(3)
		.resistance(2)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
		.requiresTool(true)

	event.create('craftoria:smokey_bricks')
		.displayName('Smokey Brick')
		.material('minecraft:deepslate_bricks')
		.hardness(3)
		.resistance(2)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)

	event.create('craftoria:smokey_bricks_slab', "slab")
		.displayName('Smokey Brick Slab')
		.material('minecraft:deepslate_bricks')
		.hardness(3)
		.resistance(2)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)

	event.create('craftoria:smokey_bricks_stairs', "stairs")
		.displayName('Smokey Brick Stairs')
		.material('minecraft:deepslate_bricks')
		.hardness(3)
		.resistance(2)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)

	event.create('craftoria:smokey_bricks_wall', "wall")
		.displayName('Smokey Brick Wall')
		.material('minecraft:deepslate_bricks')
		.hardness(3)
		.resistance(2)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)

	event.create('craftoria:smokey_bricks_button', "button")
		.displayName('Smokey Brick')
		.material('minecraft:deepslate_bricks')
		.hardness(3)
		.resistance(2)
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
		.requiresTool(true)
});
