#Defines how the jade info should be shown
#ALWAYS - Always show Jade when looking at a block
#WAND - Only show Jade when holding a wand
#NEVER - Never show Jade
#Allowed Values: ALWAYS, WAND, NEVER
jade_mode = "ALWAYS"
