# Enhanced Celestials mixin toggles.

# Overrides Minecraft's default time command with a protected/educated version of the time commands.
# /time set <day/midnight/noon/night/<time_value>> will now set the time to the next occurrence of that time for the next Minecraft day.
# /time set <day/midnight/noon/night/<time_value>> now has a 3rd argument that is "reset" which is a <true/false> value that when set to true will make this command function like its vanilla counterpart, resetting the the day time counter back to the first MC day.
# Output messages have been updated to be more clear about what the command is doing.
# This is enabled by default, but can be disabled if this mixin conflicts with another mod.
TimeCommandMixin=true
