[ui]
	#Tooltips for Developing Film Rolls and Copying Photographs will be shown on Film Rolls and Photographs respectively, describing the crafting recipe. 
	#Only when JEI is not installed. (Only JEI shows these recipes, not REI or EMI)
	recipe_tooltips_without_jei = true
	#Details about Camera configuring will be shown in Camera item tooltip.
	camera_details_tooltip = true
	#Film Roll Frames will be shown in the camera tooltip.
	#Default: true
	camera_film_frames_tooltip = true
	#Film Roll fullness bar will be shown on the Camera item.
	#Default: false
	camera_shows_film_bar = false
	#Photographer name will be shown in Photograph's tooltip.
	photograph_photographer_name_tooltip = false
	#Crosshair will not get in the way when holding a photograph.
	photograph_in_hand_hide_crosshair = true
	#When looking at the Camera Stand, in-world tooltip will show information about the camera on it. Default: true
	camera_stand_tooltip = true
	#Album will show how many photographs it contains in a tooltip.
	album_show_photos_count = true

	[ui.album]
		#Color in hex format. AARRGGBB.
		font_main_color = "FFB59774"
		#Color in hex format. AARRGGBB.
		font_secondary_color = "FFEFE4CA"
		#Color in hex format. AARRGGBB.
		selection_color = "FF8888FF"
		#Color in hex format. AARRGGBB.
		selection_unfocused_color = "FFBBBBFF"

[viewfinder]
	#Clicking middle mouse button will open Viewfinder Controls. This is independent of Open Camera Controls keybind.
	#Allows opening camera controls without dismounting from a vehicle - and keeping controls on sneak or other button as well.
	#Default: true
	middle_click_controls = true
	#How much zooming influences mouse sensitivity.
	#0 - no change to sensitivity. 1 - full effect.
	#Default: 0.75
	# Default: 0.75
	# Range: 0.0 ~ 1.0
	zoom_sensitivity_influence = 0.75
	#Color in hex format. AARRGGBB.
	background_color = "FA1F1D1B"
	#Color in hex format. AARRGGBB.
	font_main_color = "FF2B2622"
	#Color in hex format. AARRGGBB.
	font_secondary_color = "FF7A736C"
	#HUD will be hidden while looking through viewfinder. Default: true
	hide_hud_while_in_viewfinder = true
	#X offset of a viewfinder status icon. Default: 0
	# Default: 0
	# Range: -999 ~ 999
	status_icon_offset_x = 0
	#Y offset of a viewfinder status icon. Default: 0
	# Default: 0
	# Range: -999 ~ 999
	status_icon_offset_y = 0

[capture]
	#Keep Post Effect (vanilla shader) when capturing an image.
	#It is sometimes used by mods to change how player sees the world. (Cold Sweat's overheating blur, Supplementaries mob heads, for example).
	#In vanilla, it's only used when spectating a creeper/enderman/etc.
	#Default: false
	keep_post_effect = false
	#Delay in ticks before capturing an image when shooting with flash.
	#If you experience flash synchronization issues (Flash having no effect on the image) - try increasing the value.
	# Default: 4
	# Range: 1 ~ 8
	flash_capture_delay_ticks = 4
	#Force legacy (pre 1.21) capturing method for taking images. Enable if you experiencing issues with resulting images.
	#Direct method will be used regardless of this setting if mods defined in 'force_direct_capture_default_mods' is installed.
	#Default: false
	force_direct_capture = false
	#Direct capture will be used if any of these mods is installed.
	#Format: '["mod_id", "mod_id"]'. Default: [veil, pmweather]
	force_direct_capture_default_mods = ["veil", "pmweather"]
	#Delay in frames before capturing an image if 'direct_capture' method is in use.
	#Set to higher value when leftovers of GUI elements (such as nameplates) are visible on the images
	#(some shaders have temporal effects that take several frames to disappear fully)
	# Default: 0
	# Range: 0 ~ 100
	direct_capture_delay_frames = 0

[render]
	#Makes photos in Photograph Frame render with alignment to 16 pixel grid (like paintings). Just for fun. Default: false
	pixel_perfect_photograph_frame = false
	#Photographs in Item Frame will be rendered as image instead of an item icon. Default: false
	photograph_renders_in_item_frame = false
	#Projected photographs (using Interplanar Projector) made by other players will be censored (pixelated). Default: false
	censor_projected_photographs_made_by_others = false
	#All photographs made by other players will will be censored (pixelated). Default: false
	censor_all_photographs_made_by_others = false
	#Distance from the player beyond which Photograph Frame would not be rendered. Default: 64
	#Note: this number may not relate to distance in blocks exactly. It's influenced by render distance and entity distance settings.
	# Default: 64
	# Range: 8 ~ 128
	photograph_frame_culling_distance = 64
	#Depth offset to Photograph in Photograph Frame. Can be used to fix issues with some 3D resourcepacks. Value of 0.015 is good for 'Classic 3D' resourcepack. Default: 0.0
	# Default: 0.0
	# Range: -1.0 ~ 1.0
	photograph_frame_image_offset = 0.0

[integration]
	#Useful information about some items will be shown in JEI description category. Default: true
	jei_information = true
	#[Real Camera] Disable player model rendering when looking through viewfinder. Default: true
	real_camera_disable_in_viewfinder = true

[export]
	#When the Photograph you took is viewed in UI (by using a Photograph), image will be exported to '<instance>/exposures' folder as a png.
	export_viewed_photographs = true
	#When exporting, exposures will be organized to subfolders with world name.
	export_organize_by_world = true
	#Exported exposures will be scaled by this multiplier.
	#Given the default exposure size of 320 pixels - this will produce:
	#320/640/960/1280/etc image. Be careful with larger frame sizes.
	#Default: 2
	# Default: 2
	# Range: 1 ~ 10
	export_size_multiplier = 2

[tutorial]
	#Toast that teaches hovering mouse over camera parts will be shown when attachments menu is first opened. Default: true.
	#*This setting will be automatically set to false on first show.*
	attachments_show_info_toast = true
	#Toast that teaches wiki opening will be shown when attachments menu is first opened, after info toast. Default: true.
	#*This setting will be automatically set to false on first show.*
	attachments_show_wiki_toast = true
