[misc]
	#Signed Album item will have an enchantment glint.
	signed_album_glint = true
	#Mundane, Awkward and Thick potions will have their color changed slightly, so it's easier to tell them apart. Default: true
	different_developing_potions_colors = true
	#Generate photographs and film rolls in loot chests. Default: true
	loot_chests = true
