[ui]
	#Details about Camera configuring will be shown in Instant Camera item tooltip.
	instant_camera_details_tooltip = true
	#Slides count will be shown in the Instant Camera item tooltip.
	#Default: true
	instant_camera_slides_tooltip = true
	#Slide fullness bar will be shown on the Instant Camera item.
	#Default: false
	instant_camera_shows_slides_bar = false

[viewfinder]
	#Color in hex format. AARRGGBB.
	background_color = "FA1F1D1B"
	#Color in hex format. AARRGGBB.
	font_main_color = "FF2B2622"
	#Color in hex format. AARRGGBB.
	font_secondary_color = "FF7A736C"
