[client]
	#是否显示样板编码玩家
	#开启后将在样板 HoverText 上添加样板的编码玩家
	showEncoderPatternPlayer = true
	#样板终端默认是否显示槽位
	#影响进入界面时SlotsRow的默认可见性，仅影响客户端显示
	patternTerminalShowSlotsDefault = true
	#JEI 中是否显示 AE2 网络库存与可合成状态
	#可通过 JEI 左下角按钮即时切换
	jeiNetworkOverlayEnabled = true
	#扩展样板供应器是否显示倍率调整按钮
	#可通过扩展样板供应器左侧工具栏即时切换
	extendedPatternProviderShowScalingControls = true
