accessories.roundabout_collection=true

ae2.cache_fuzzy_search_max_value=true

botanypots.hopper_insertions=true

create.fail_fast_clipboard_migration=true

pastel.nuke_item_predicate_mixin=true

pipez.constant_fullness_checks=true
pipez.early_exits=true
pipez.extract_looped_work=true
pipez.filter_caching=false
pipez.nbt_comparisons=true
pipez.stream_abuse=true

placebo.lazy_string_concatenation=true
placebo.streamless_hashing=true

sfm.filter_caching=false

xycraft_machines.redstone_checks=true
xycraft_machines.unnecessary_resorting=true
