#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Mar 12 09:31:37 CET 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=16
shaderPack=ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6
