#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 00:27:44 CEST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=16
shaderPack=ComplementaryUnbound_r5.9 + EuphoriaPatches_1.10.0
