#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 30 05:03:51 CEST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=16
shaderPack=ComplementaryUnbound_r5.8.1 + EuphoriaPatches_1.9.3
