[tab]
	#Whether to open the upgrade terminal panel when the terminal is opened.
	openSidePanel = false
	#Whether to show the upgrade panel toggle button in the terminal left toolbar.
	showUpgradePanelButton = true
	#Whether terminals should expose view cell slots.
	showViewCellSlots = true
