#Disables ghost previews when trying to place a multiblock
"Disable Multiblock Previews" = false
#Enables previews for everything, Used for debugging
"Previews for Everything" = false
#List of blocks for which to show previews
"Preview Whitelist" = []
#List of blocks for which to hide previews
"Preview Blacklist" = []
