# Whether to allow retrieving the last couple deleted items from the trash can screen
# Allowed values: true, false - Default: true
retrieveDeletedItems = true

# Can radioactive fluids from Mekanism be voided?
# Allowed values: true, false - Default: false
allowVoidingNuclearWaste = false

