#A list of items to blacklist from being distributed by luck.
blacklisted_items = ["minecraft:map", "ars_additions:exploration_warp_scroll", "ars_nouveau:exploration_scroll", "the_bumblezone:honey_compass"]
