["Bundles of Bravery"]
	#toggle the updated controls and UI for bundles
	has_updated_bundles = true
	#allow bundles to appear on chests at villages
	bundle_loot = true
	#toggle the modern rendering for bundles
	has_modern_bundle_graphics = true
	#toggle whether bundles should be dyeable
	has_dyeable_bundle_recipe = true

["The Garden Awakens"]
	#allow resin to be obtainable from creaking hearts
	resin = true
	#allow resin to appear on chests at woodland mansions
	resin_loot = true
	#allow creakings to spawn from creaking hearts
	creaking = true
	#allow the pale garden to generate in the overworld
	pale_garden = true
	#allow features from 'The Garden Awakens' to be obtainable through wandering traders
	pale_trades = true
	#creaking heart trail particle color (gray by default)
	creaking_particle_color = 6250335
	#creaking heart trail particle reverse color (orange by default)
	creaking_particle_reverse_color = 16545810
	#allow Creaking Hearts to generate Creakings even during the day
	do_creaking_hearts_work_on_day = false

["Spring to Life"]
	#allow bushes to generate in the overworld
	bushes = true
	#allow firefly bushes to generate in the overworld
	firefly_bushes = true
	#allow wildflowers to generate in the overworld
	wildflowers = true
	#allow dry grass to generate in the overworld
	dry_grass = true
	#allow fallen trees to generate in the overworld
	fallen_trees = true
	#allow leaf litter to generate in the overworld
	leaf_litter = true
	#allow cactus flowers to generate
	cactus_flowers = true
	#allow variants for pigs, cows and chickens to generate
	farm_animal_variants = true
	#allow wolfs to have variants for their sounds
	wolf_sound_variants = true
	#allow features from 'Spring to Life' to be obtainable through wandering traders
	spring_trades = true
	#allow camels to spawn outside of villages
	camel_spawns = true
	#allow lodestones to appear on chests at ruined portals
	lodestone_loot = true

["Chase the Skies"]
	#allow dried ghasts to be obtainable through nether fossils and piglin bartering
	dried_ghasts = true
	#toggle whether leashes drop their connections when boosting with a firework rocket
	leash_drop_connections = true
	#allows ghasts drop the tears music disc
	tears_music_disc = true
	#apply a modifier to the speed of happy ghasts when ridden, 1.0 is default speed
	happy_ghast_speed_modifier = 1.0

["Hot as Lava"]
	#allows chicken jockeys to drop the lava chicken music disc
	lava_chicken_music_disc = true

["Chaos Cubed"]
	#allow the generation of Sulfur Cave biomes
	has_sulfur_caves = true
	#allow the generation of Sulfur Springs on top of Sulfur Caves
	has_sulfur_springs = true
	#allow Potent Sulfur Blocks to generate Geysers
	do_geysers_erupt = true
	#allow Sulfur Cubes to spawn on Sulfur Caves
	has_sulfur_cubes = true
	#allow Sulfur Cubes with exploding archetypes to explode
	do_sulfur_cubes_explode = true
	#allow Sulfur Cubes with damaging archetypes to deal damage
	do_sulfur_cubes_damage = true
	#allow Wanderer traders to sell contents from Chaos Cubed
	do_merchant_trade_chaos_cubed_contents = true
	#allows the bounce music disc to generate on abandoned mineshafts
	has_bounce_music_disc = true
