abilitiesData:
    abilities:
        camouflage:
            # Highest level to which the ability can be upgraded
            maxLevel: 10
            # Relic level at which the ability becomes unlocked
            requiredLevel: 0
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                heal:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 0.25
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 0.1
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Type of mathematical operation used to calculate the stat's value based on the ability level.
                    scalingModel: relics:logarithmic
                    # Value the stat reaches when both the stat quality and ability level are at their maximum.
                    targetValue: 2.50009
                absorption:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 3.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 1.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Type of mathematical operation used to calculate the stat's value based on the ability level.
                    scalingModel: relics:multiplicative_base
                    # Value the stat reaches when both the stat quality and ability level are at their maximum.
                    targetValue: 19.9995
                cooldown:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 10.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 15.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 0.0
                    # Type of mathematical operation used to calculate the stat's value based on the ability level.
                    scalingModel: relics:multiplicative_base
                    # Value the stat reaches when both the stat quality and ability level are at their maximum.
                    targetValue: 4.9985
        revival:
            # Highest level to which the ability can be upgraded
            maxLevel: 10
            # Relic level at which the ability becomes unlocked
            requiredLevel: 5
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                radius:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 10.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 5.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Type of mathematical operation used to calculate the stat's value based on the ability level.
                    scalingModel: relics:exponential
                    # Value the stat reaches when both the stat quality and ability level are at their maximum.
                    targetValue: 24.97833
                heal:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 1.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 0.5
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Type of mathematical operation used to calculate the stat's value based on the ability level.
                    scalingModel: relics:logarithmic
                    # Value the stat reaches when both the stat quality and ability level are at their maximum.
                    targetValue: 4.99992
                damage:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 1.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 0.5
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Type of mathematical operation used to calculate the stat's value based on the ability level.
                    scalingModel: relics:logarithmic
                    # Value the stat reaches when both the stat quality and ability level are at their maximum.
                    targetValue: 4.99992
                paralysis:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 1.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 0.5
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Type of mathematical operation used to calculate the stat's value based on the ability level.
                    scalingModel: relics:logarithmic
                    # Value the stat reaches when both the stat quality and ability level are at their maximum.
                    targetValue: 4.99992
levelingData:
    # Amount of experience required to level up to relic level 1
    initialCost: 100.0
    # Increment in experience required for each subsequent level of the relic
    step: 200.0
lootData:
    # List of conditions for obtaining the relic. Supports both direct ID specification and regular expressions.
    entries:
    -   biomes:
        - '[\w]+:.*(forest|wood|timberland|silva|wildwood|garden|grove)[\w_\/]*'
        dimensions:
        - .*
        tables:
        - '[\w]+:chests\/[\w_\/]*[\w]+[\w_\/]*'
        weight: 300
    -   biomes:
        - '[\w]+:.*(jungle|rainforest|tropic|wildwood|thicket|boscage|humid|bamboo)[\w_\/]*'
        dimensions:
        - .*
        tables:
        - '[\w]+:chests\/[\w_\/]*[\w]+[\w_\/]*'
        weight: 300
